# Generated by Django 4.1.1 on 2023-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_product_stock_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='pic4',
        ),
        migrations.AddField(
            model_name='buyer',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
    ]
