# Generated by Django 4.1.7 on 2023-03-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='product',
        ),
    ]
